### ISSUE TITLE
( BUG Whitaker's Words Current Version 2.0.0 ) After opening the application, the application crashes after I click on the back button

### ISSUE THREAD

**Issue by friendsmobile** [ids1024/whitakers-words-android#5]
# Project Information

* Repository:  https://github.com/ids1024/whitakers-words-android
* Project Name:  Whitaker's Words
* My Github Account: https://github.com/friendsmobile
* Download the application:  https://play.google.com/store/apps/details?id=com.ids1024.whitakerswords

# Expected behavior

After opening the application, the application should not crash when I click on the back button

# Actual behavior

After opening the application, the application crashes after I click on the back button

#### How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=com.ids1024.whitakerswords)the application
*  open the Application 
* click on the back button or try to back the application page 
* Note the Error

* Browser/App version: Current Version 2.0.0
* Operating system: 6.0

#### Recording Of The Bug

![20190714_150346](https://user-images.githubusercontent.com/51118734/61182175-8c828000-a5e4-11e9-98f2-9986b5d8db95.gif)

#### Logcat

<pre><code>D/AndroidRuntime(14352): Shutting down VM

E/AndroidRuntime(14352): FATAL EXCEPTION: main

E/AndroidRuntime(14352): Process: com.ids1024.whitakerswords, PID: 14352

E/AndroidRuntime(14352): java.lang.RuntimeException

E/AndroidRuntime(14352): 	at com.ids1024.whitakerswords.WhitakersWords$onCreate$2.onBackStackChanged(WhitakersWords.kt:42)

E/AndroidRuntime(14352): 	at android.support.v4.app.FragmentManagerImpl.reportBackStackChanged(FragmentManager.java:2704)

E/AndroidRuntime(14352): 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)

E/AndroidRuntime(14352): 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)

E/AndroidRuntime(14352): 	at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:854)

E/AndroidRuntime(14352): 	at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:797)

E/AndroidRuntime(14352): 	at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:186)

E/AndroidRuntime(14352): 	at android.app.Activity.onKeyUp(Activity.java:2556)

E/AndroidRuntime(14352): 	at android.view.KeyEvent.dispatch(KeyEvent.java:3189)

E/AndroidRuntime(14352): 	at android.app.Activity.dispatchKeyEvent(Activity.java:2811)

E/AndroidRuntime(14352): 	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)

E/AndroidRuntime(14352): 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)

E/AndroidRuntime(14352): 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)

E/AndroidRuntime(14352): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2514)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4103)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4065)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3680)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3646)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3763)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3654)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3820)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3680)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3646)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3654)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3680)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3646)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3796)

E/AndroidRuntime(14352): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3957)

E/AndroidRuntime(14352): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2325)

E/AndroidRuntime(14352): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1919)

E/AndroidRuntime(14352): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1910)

E/AndroidRuntime(14352): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2302)

E/AndroidRuntime(14352): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)

E/AndroidRuntime(14352): 	at android.os.MessageQueue.nativePollOnce(Native Method)

E/AndroidRuntime(14352): 	at android.os.MessageQueue.next(MessageQueue.java:143)

E/AndroidRuntime(14352): 	at android.os.Looper.loop(Looper.java:122)

E/AndroidRuntime(14352): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(14352): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(14352): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(14352): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(14352): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by ids1024** [comment]
Thanks for the detailed bug report! I haven't been able to reproduce the issue, but I *think* b4af3621ca9dca6835cd3801020a57f6f5c0b416 should fix it.

**Comment by friendsmobile** [comment]
but this   bug is  still avaliable

**Comment by ids1024** [comment]
I wrote that commit just before commenting, so it hasn't been released.

You can try building from git, or downloading a prebuilt apk from [Bintray](https://bintray.com/ids1024/whitakers-words-android/master).

**Comment by friendsmobile** [comment]
can you provide me apk link where i can download the  latest version of application

**Comment by ids1024** [comment]
This is the APK built by Travis for the last commit: https://bintray.com/ids1024/whitakers-words-android/download_file?file_path=whitakers-words-android-debug-r218.30001de.apk

**Comment by friendsmobile** [comment]
@ids1024   your new .apk file can not be installed on my mobile phone

**Comment by ids1024** [comment]
It's a debug build, so it's signed with a different key. You have to uninstall the app first, then install the apk for it to work.

**Comment by friendsmobile** [comment]
I have already uninstalled the application
